# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stick_breaking_init <- function(K, alpha) {
    .Call(`_DPGLM_stick_breaking_init`, K, alpha)
}

stick_breaking_update <- function(K, alpha, z) {
    .Call(`_DPGLM_stick_breaking_update`, K, alpha, z)
}

sample_cluster_assignments <- function(data, pi, mu, sigma2) {
    .Call(`_DPGLM_sample_cluster_assignments`, data, pi, mu, sigma2)
}

sample_cluster_parameters <- function(data, z, sigma2, mu, K, mu0, sigma02, a_sigma, b_sigma) {
    .Call(`_DPGLM_sample_cluster_parameters`, data, z, sigma2, mu, K, mu0, sigma02, a_sigma, b_sigma)
}

update_alpha <- function(alpha, n, K, a, b) {
    .Call(`_DPGLM_update_alpha`, alpha, n, K, a, b)
}

update_mu0 <- function(mu, sigma02) {
    .Call(`_DPGLM_update_mu0`, mu, sigma02)
}

update_sigma02 <- function(mu, mu0, a0, b0) {
    .Call(`_DPGLM_update_sigma02`, mu, mu0, a0, b0)
}

slice_sampler_a_sigma <- function(a_sigma, shape, rate, sigma2, b_sigma, w = 0.1, m = 20L) {
    .Call(`_DPGLM_slice_sampler_a_sigma`, a_sigma, shape, rate, sigma2, b_sigma, w, m)
}

update_b_sigma <- function(d0, e0, sigma2, a_sigma) {
    .Call(`_DPGLM_update_b_sigma`, d0, e0, sigma2, a_sigma)
}

dirichlet_process_mixture_sampler <- function(data, n_iter, alpha, mu0, sigma02, a, b, a0, b0, c0, d0, e0, f0, max_clusters) {
    .Call(`_DPGLM_dirichlet_process_mixture_sampler`, data, n_iter, alpha, mu0, sigma02, a, b, a0, b0, c0, d0, e0, f0, max_clusters)
}

b_theta <- function(s_k, f_k, theta_i) {
    .Call(`_DPGLM_b_theta`, s_k, f_k, theta_i)
}

b_prime_theta <- function(s_k, f_k, theta_i) {
    .Call(`_DPGLM_b_prime_theta`, s_k, f_k, theta_i)
}

L_theta <- function(s_k, f_k, theta_i, c_0, y) {
    .Call(`_DPGLM_L_theta`, s_k, f_k, theta_i, c_0, y)
}

llik_beta <- function(y, x, theta, crm, c_0, B, sigma_theta) {
    .Call(`_DPGLM_llik_beta`, y, x, theta, crm, c_0, B, sigma_theta)
}

crm_sampler <- function(M, u, zstar, nstar, tht, alpha, mu, y, z_tld, J_tld) {
    .Call(`_DPGLM_crm_sampler`, M, u, zstar, nstar, tht, alpha, mu, y, z_tld, J_tld)
}

logpdf_unif <- function(x, lower, upper) {
    .Call(`_DPGLM_logpdf_unif`, x, lower, upper)
}

rmvnorm <- function(mean, Precision) {
    .Call(`_DPGLM_rmvnorm`, mean, Precision)
}

rcategorical <- function(probs) {
    .Call(`_DPGLM_rcategorical`, probs)
}

mvrnormArma <- function(R, mu, sigma) {
    .Call(`_DPGLM_mvrnormArma`, R, mu, sigma)
}

log_posterior_u <- function(u, z, theta, alpha) {
    .Call(`_DPGLM_log_posterior_u`, u, z, theta, alpha)
}

psi <- function(z, u, tht) {
    .Call(`_DPGLM_psi`, z, u, tht)
}

psi_zstar <- function(zstar, u, tht) {
    .Call(`_DPGLM_psi_zstar`, zstar, u, tht)
}

u_sampler <- function(u_old, z, theta, alpha, delta) {
    .Call(`_DPGLM_u_sampler`, u_old, z, theta, alpha, delta)
}

z_sampler <- function(y, c0, theta, crm_mat) {
    .Call(`_DPGLM_z_sampler`, y, c0, theta, crm_mat)
}

